actions_path '../VerizonVideoPartnerSDK-build-scripts-ios/cocoapods'

before_all do |lane, options|
  xcversion(version: '~> 11.6')
end

default_platform(:ios)

platform :ios do
  lane :test do
    scan(
      fail_build: true,
      scheme: 'PlayerCore'
      )
  end
  lane :lint_current_podspec do 
    lint_podspec(
      podspec_path: './podspec/PlayerCore.podspec',
      sources_repo: 'https://github.com/VerizonAdPlatforms/VerizonVideoPartnerSDK-releases-iOS')
  end  
end
