actions_path '../OneMobileSDK-build-scripts-ios/cocoapods'

default_platform(:ios)

platform :ios do
  lane :test do
    scan(
      fail_build: true,
      scheme: 'PlayerCore'
      )
  end
  lane :lint_current_podspec do 
    lint_podspec(
      podspec_path: './podspec/PlayerCore.podspec',
      sources_repo: 'https://github.com/VerizonAdPlatforms/OneMobileSDK-releases-iOS')
  end  
end
